services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    restart: always
    networks:
      - it-tools-net
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.tls.certresolver=letsencrypt"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes: {}

networks:
  it-tools-net:
    driver: bridge
  dokploy-network:
    external: true
